# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_poker_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokeduser', to='mainapp.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokeruser', to='mainapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='poker',
            name='poker',
        ),
        migrations.RemoveField(
            model_name='poker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poker',
        ),
    ]
